"""empty message

Revision ID: cf1c366e806a
Revises: 
Create Date: 2021-11-27 20:26:07.364189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf1c366e806a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('language_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_language_types_id'), 'language_types', ['id'], unique=False)
    op.create_index(op.f('ix_language_types_type'), 'language_types', ['type'], unique=True)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_table('company_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_type_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['language_type_id'], ['language_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_names_id'), 'company_names', ['id'], unique=False)
    op.create_index(op.f('ix_company_names_name'), 'company_names', ['name'], unique=False)
    op.create_table('company_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_tags_id'), 'company_tags', ['id'], unique=False)
    op.create_table('tag_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_type_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['language_type_id'], ['language_types.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_names_id'), 'tag_names', ['id'], unique=False)
    op.create_index(op.f('ix_tag_names_name'), 'tag_names', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_names_name'), table_name='tag_names')
    op.drop_index(op.f('ix_tag_names_id'), table_name='tag_names')
    op.drop_table('tag_names')
    op.drop_index(op.f('ix_company_tags_id'), table_name='company_tags')
    op.drop_table('company_tags')
    op.drop_index(op.f('ix_company_names_name'), table_name='company_names')
    op.drop_index(op.f('ix_company_names_id'), table_name='company_names')
    op.drop_table('company_names')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_language_types_type'), table_name='language_types')
    op.drop_index(op.f('ix_language_types_id'), table_name='language_types')
    op.drop_table('language_types')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
